apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-redirect-proxy
  labels:
    team: yts-core
    git.yolt.io/group: backend
    git.yolt.io/project: client-redirect-proxy
    git.yolt.io/tag: $(TAG)
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: client-redirect-proxy
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/agent-revoke-on-shutdown: "true"
        vault.hashicorp.com/agent-revoke-grace: "185"
        vault.hashicorp.com/role: client-redirect-proxy
        vault.hashicorp.com/agent-cache-enable: "false"
        vault.hashicorp.com/agent-pre-populate: "true" # Makes vault-agent prepare the cert/key prior to nginx starting.
        vault.hashicorp.com/secret-volume-path: /vault/secrets
        vault.hashicorp.com/auth-path: "auth/$(ENVIRONMENT)/k8s/eks/pods/$(NAMESPACE)"
        vault.hashicorp.com/agent-limits-cpu: 1000m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-cpu: 10m
        vault.hashicorp.com/agent-requests-mem: 24Mi
        vault.hashicorp.com/agent-inject-secret-cert: ""
        vault.hashicorp.com/agent-inject-template-cert: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-redirect-proxy" "common_name=client-redirect-proxy" }}
          {{- .Data.certificate -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-private_key: ""
        vault.hashicorp.com/agent-inject-template-private_key: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-redirect-proxy" "common_name=client-redirect-proxy" }}
          {{- .Data.private_key -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-issuing_ca: ""
        vault.hashicorp.com/agent-inject-template-issuing_ca: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-redirect-proxy" "common_name=client-redirect-proxy" }}
          {{- .Data.issuing_ca -}}
          {{ end }}
        vault.hashicorp.com/client-max-retries: "4"
        ca-certificates.yolt.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9443"
        prometheus.io/scheme: https
      labels:
        team: yts-core
        serving: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - client-redirect-proxy
                topologyKey: topology.kubernetes.io/zone
      containers:
        - name: client-redirect-proxy
          image: $(DOCKER_REGISTRY)/client-redirect-proxy:$(DOCKER_TAG)
          ports:
            - containerPort: 8443
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 2
          livenessProbe:
            httpGet:
              path: /probe/liveness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 1
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /probe/readiness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 1
          resources:
            limits:
              memory: 16Mi
            requests:
              cpu: 200m
              memory: 8Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 100
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 100
      serviceAccountName: client-redirect-proxy
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: tmp-volume
