apiVersion: v1
kind: Service
metadata:
  name: client-redirect-proxy
  labels:
    team: yts-core
spec:
  selector:
    name: client-redirect-proxy
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
